name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - dask
  - distributed
  - gcsfs
  - intake::intake
  - intake::intake-xarray
  - scikit-image
  - scikit-learn
  - dask-ml
  - bokeh
  - pyviz/label/earthsim::holoviews
  - pyviz/label/earthsim::panel
  - geoviews
  - hvplot
  - rasterio
  - datashader
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - jupyterlab
  - ipywidgets
  - graphviz
  - dask-kubernetes
